 ---
 
 - hosts: all
   become: true
   pre_tasks:
   
   - name: update repository index (Zorin)
     tags: always
     apt:
       update_cache: yes
     changed_when: false
     when: ansible_distribution == "Zorin"
 
 - hosts: all
   become: true
   roles:
     - base
    
 - hosts: windows
   become: true
   roles:
     - workstations

 - hosts: linux
   become: true
   roles:
     - workstations
