---

- name: Check for packages to include
  ansible.builtin.set_fact:
    accept_packages: "{{ whitelist.split(',') }}"
  when: whitelist != ''

- name: Check for packages to exclude
  ansible.builtin.set_fact:
    reject_packages: "{{ blacklist.split(',') }}"
  when: blacklist != ''

  - name: Install Windows Updates
    ansible.windows.win_updates:
      category_names: "{{ categoies | default('*') }}"
      reboot: "{{ reboot_server | default('true') }}"
      whitelist: "{{ accept_packages | default(omit) }}"
      blacklist: "{{ reject_packages | default(omit) }}"
    register: patchresult

    
