---

- hosts: linux
  become: true
  tasks:
  
  - name: Perform full upgrade on OS and Install Packages
    package:
      name:
        - Discord
        - Lutris
      state: latest
      update_cache: yes
      upgrade: dist
      when: ansible_distribution == "Zorin"
