---

- hosts: linux
  become: true
  tasks:
  
  - name: Perform full upgrade on OS
    apt:
      update_cache: yes
      upgrade: yes

  - name: Install packages
    apt:
      name:
        Discord
        Lutris
      state: latest
